apiVersion: v1
kind: Service
metadata:
  name: sound-realty-ml-app-service
spec:
  selector:
    app: sound-realty-ml-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
